name: check build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master, dev/* ]

jobs:
  build-linux:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        target: 
          - x86_64-unknown-linux-musl
          - aarch64-unknown-linux-musl
          - i686-unknown-linux-musl
          #- x86_64-apple-darwin
          #- aarch64-apple-darwin
          - x86_64-pc-windows-gnu
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: install g++-aarch64-linux-gnu
        if: ${{ matrix.target == 'aarch64-unknown-linux-musl' }}
        run: sudo apt-get install g++-aarch64-linux-gnu
      - name: install mingw-w64
        if: ${{ matrix.target == 'x86_64-pc-windows-gnu' || matrix.target == 'i686-pc-windows-gnu' }}
        run: sudo apt-get install mingw-w64
      - name: Setup rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          target: ${{ matrix.target }}
          override: true
      - name: Release build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --target ${{ matrix.target }} --release
      - run: ls -l target/${{ matrix.target }}/release/
