name: check build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master, dev/* ]

jobs:
  build-linux:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        target: [x86_64-unknown-linux-musl, aarch64-unknown-linux-musl, i686-unknown-linux-musl]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          target: ${{ matrix.target }}
          override: true
      - name: Release build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release
      - run: ls -l target/release/cece
