name: Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master, dev/* ]

jobs:
  diff_test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
      - run: echo $PATH
      - run: cargo version
      - run: cargo build --verbose
      - run: bash test.sh
