name: Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master, dev/* ]

jobs:
  diff_test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: ture
          default: ture
      - run: which cargo
      - run: ls /usr/share/rust/.cargo/bin/
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: version
      - run: cargo version
      - run: cargo build --verbose
      - run: bash test.sh
